<div class="hero-unit">
    <h1>Welcome to <span class="zf-green">Zend Framework</span></h1>
    <p>Congratulations! You have successfully installed the <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF2 Skeleton Application%s. You are currently running Zend Framework version</a>. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.</p>
    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank">Fork Zend Framework 2 on GitHub</a>.</p>
</div>

<div class="row">

    <div class="span4">
        <h2>Follow Development</h2>
        <p>Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework webiste which provides links to the ZF2 <a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">wiki</a>.</p>
    </div>

</div>
